jwt.key.public=classpath:app.pub

jwt.key.private=classpath:app.key

spring.application.name=ecommerce-1
spring.datasource.url=jdbc:h2:mem:mydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.settings.web-allow-others=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update